#include "mapgeneration.hpp"
#include <fstream>
#include <iostream>
#include <filesystem>
#include "..\..\utility\logger\logger.hpp"

sf::Vector2f randomGradient(int ix, int iy, unsigned int seed) {
    //Hashing
    const unsigned intWidth = 8 * sizeof(unsigned);
    const unsigned halfintWidth = intWidth / 2;
    unsigned a = ix, b = iy;

    a ^= seed;
    b ^= seed;

    a *= 3284157443;

    b ^= a << halfintWidth | a >> intWidth - halfintWidth;
    b *= 1911520717;

    a ^= b << halfintWidth | b >> intWidth - halfintWidth;
    a *= 2048419325;

    //creating vector
    float randomAngle = a * (3.14159265 / ~(~0u >> 1));

    sf::Vector2f gradient;
    gradient.x = sin(randomAngle);
    gradient.y = cos(randomAngle);

    return gradient;
}

float dotProduct(int ix, int iy, float x, float y, unsigned int seed) {

    sf::Vector2f gradient = randomGradient(ix, iy, seed);

    float dx = x - (float)ix;
    float dy = y - (float)iy;

    return (dx * gradient.x + dy * gradient.y);
}

float interpolation(float a0, float a1, float w) {
    return (a1 - a0) * (3.0f - w * 2.0f) * w * w + a0;
}

float perlin(float x, float y, unsigned int seed) {

    //corners
    int x0 = floor(x);
    int y0 = floor(y);
    int x1 = x0 + 1;
    int y1 = y0 + 1;

    //interpolation weights
    float xWeight = x - (float)x0;
    float yWeight = y - (float)y0;

    //top 2 corners
    float n0 = dotProduct(x0, y0, x, y, seed);
    float n1 = dotProduct(x1, y0, x, y, seed);
    float ix0 = interpolation(n0, n1, xWeight);

    //bottom 2 corners
    n0 = dotProduct(x0, y1, x, y, seed);
    n1 = dotProduct(x1, y1, x, y, seed);
    float ix1 = interpolation(n0, n1, xWeight);

    float value = interpolation(ix0, ix1, yWeight);

    return value;
}

void generateMap(std::string name, int windowWidth, int windowHeight) {

    if (std::filesystem::exists(name)) {
        std::string decide;
        std::cout << "Map found, Load the found Map?\nL - load the map\nG - generate a new map\n";
        do {
            std::cin >> decide;
            if (decide == "L" || decide == "l") {
                return;
            }
            else if (decide == "G" || decide == "g") {
                break;
            }
            else {
                std::cout << "Command not recognized\nL - load the new map\nG - generate a new map\n";
            }
        } while (true);
    }
    else {
        std::cout << "No map found";
    }

    unsigned int seed = 0;
    std::string seedInText;
    std::cout << "Input Map Seed:\n";
    std::getline(std::cin >> std::ws, seedInText);
    for (char c : seedInText) {
        if (seed >= 2147482648) {
            break;
        }
        seed *= 2;
        seed += abs(static_cast<int>(c));
    }

    std::ofstream mapFile(name);
    mapFile << "#AutoGeneratedMap\n";
    mapFile << "width: "<<windowWidth<<"\nheight: "<<windowHeight<<"\n";
    mapFile << "data:";

    defaultLogger.infoLog("Generating map...");

    int GRID_SIZE = 40;
    
    for (int y = 1; y <= windowHeight; y++)
    {
        for (int x = 1; x <= windowWidth; x++)
        {
            
            float val = 0;
            float freq = 1;
            float amp = 1;
             
            for (int i = 0; i < 5; i++) //octaves
            {
                val += perlin(x * freq / GRID_SIZE, y * freq / GRID_SIZE, seed) * amp;

                freq *= 2;
                amp /= 2;

            }

            // Contrast
            val *= 1.3;

            // Clipping
            if (val > 1.0f)
                val = 1.0f;
            else if (val < -1.0f)
                val = -1.0f;

            val = (int)(((val + 1.0f) * 0.5f)*3.99);

            mapFile << " " << val;
        }
    }
    mapFile.close();
    defaultLogger.successLog("Map Generated");
}